const jokes = [
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Why was the math book sad? It had too many problems.",
    "What do you call fake spaghetti? An impasta.",
    "Why don’t eggs tell jokes? They’d crack each other up.",
    "How does a penguin build its house? Igloos it together.",
    "Why was the computer cold? It left its Windows open.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Why are elevator jokes so good? They work on many levels.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call a belt made of watches? A waist of time.",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a fish with no eyes? Fsh.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why don’t skeletons ever go trick or treating? Because they have no body to go with.",
    "What did the grape do when it got stepped on? It let out a little wine.",
    "Why did the bicycle fall over? It was two tired.",
    "Why don’t oysters donate to charity? Because they are shellfish.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "What do you call a factory that makes OK products? A satisfactory.",
    "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
    "What do you call a can opener that doesn’t work? A can’t opener.",
    "Why was the stadium so hot? All the fans left.",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What do you call a dog magician? A labracadabrador.",
    "Why did the orange stop? It ran out of juice.",
    "Why couldn’t the pony sing a lullaby? She was a little horse.",
    "What do you call an alligator in a vest? An investigator.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
    "What do you call a parade of rabbits hopping backward? A receding hare-line.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "What do you call a boomerang that won’t come back? A stick.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "What do you call a group of musical whales? An orca-stra.",
    "Why was the big cat disqualified from the race? Because it was a cheetah.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "What do you call a bee that can’t make up its mind? A maybee.",
    "Why don’t teddy bears eat dessert? They’re always stuffed.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the frog take the bus to work? His car got toad.",
    "What kind of music do mummies listen to? Wrap music.",
    "Why did the banana go to the doctor? It wasn’t peeling well.",
    "What do you call a pile of cats? A meowtain.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the cookie go to the doctor? It felt crumby.",
    "Why did the coffee call it quits? It couldn’t espresso itself anymore.",
    "Why did the bicycle fall over? It was two-tired.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "Why do fish live in salt water? Because pepper makes them sneeze.",
    "Why was the broom late? It swept in.",
    "Why don’t ants get sick? They have tiny ant-bodies.",
    "What do you call a cow in an earthquake? A milkshake.",
    "What do you get when you cross a vampire and a snowman? Frostbite.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "Why did the football team go to the bank? To get their quarterback.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "Why are frogs so happy? They eat whatever bugs them.",
    "Why did the picture go to jail? Because it was framed.",
    "What do you call a funny mountain? Hill-arious.",
    "Why can’t your hand be 12 inches long? Because then it’d be a foot.",
    "Why do ducks have feathers? To cover their butt-quacks.",
    "Why don’t vampires like garlic? Because it’s a pain in the neck.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "Why can’t you give Elsa a balloon? Because she’ll let it go.",
    "What do you call a fake noodle? An impasta.",
    "Why did the skeleton go to the party alone? He had no body to go with.",
    "Why don’t you write with a broken pencil? Because it’s pointless.",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why don’t programmers like nature? It has too many bugs.",
    "Why do vampires always seem sick? They’re always coffin.",
    "What’s a skeleton’s least favorite room in the house? The living room.",
    "Why was the math book sad? It had too many problems.",
    "Why did the student eat his homework? Because the teacher said it was a piece of cake.",
    "Why do cows wear bells? Because their horns don’t work.",
    "Why did the tree go to the barber? It needed a trim.",
    "Why are ghosts bad liars? Because you can see right through them.",
    "What do you call a sleeping bull? A bulldozer.",
    "What did the duck say when it bought lipstick? Put it on my bill.",
    "What’s a pirate’s favorite letter? You’d think it’s R, but it’s the C."
  ];
  
 module.exports = jokes;
  